// Base de datos de productos de electrodomésticos
const products = [
  // COMPUTADORAS (10 productos)
  {
    id: 1,
    name: 'Notebook HP Pavilion 15.6"',
    price: 450000,
    category: "computadoras",
    brand: "HP",
    description: "Notebook HP Pavilion con procesador Intel Core i5, 8GB RAM, 256GB SSD. Ideal para trabajo y estudio.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 5,
    specs: {
      Procesador: "Intel Core i5-1135G7",
      RAM: "8GB DDR4",
      Almacenamiento: "256GB SSD",
      Pantalla: '15.6" Full HD',
      Sistema: "Windows 11",
    },
  },
  {
    id: 2,
    name: "PC Gamer AMD Ryzen 5",
    price: 680000,
    category: "computadoras",
    brand: "AMD",
    description: "PC Gamer completa con AMD Ryzen 5, 16GB RAM, RTX 3060, perfecta para gaming y streaming.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 0,
    specs: {
      Procesador: "AMD Ryzen 5 5600X",
      RAM: "16GB DDR4",
      "Tarjeta Gráfica": "RTX 3060 12GB",
      Almacenamiento: "500GB SSD + 1TB HDD",
      Fuente: "650W 80+ Bronze",
    },
  },
  {
    id: 3,
    name: 'MacBook Air M2 13"',
    price: 1200000,
    category: "computadoras",
    brand: "Apple",
    description: "MacBook Air con chip M2, diseño ultradelgado, batería de larga duración.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Chip: "Apple M2",
      RAM: "8GB",
      Almacenamiento: "256GB SSD",
      Pantalla: '13.6" Liquid Retina',
      Batería: "Hasta 18 horas",
    },
  },
  {
    id: 4,
    name: "Lenovo ThinkPad E14",
    price: 520000,
    category: "computadoras",
    brand: "Lenovo",
    description: "Notebook empresarial Lenovo ThinkPad, robusto y confiable para uso profesional.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 8,
    specs: {
      Procesador: "Intel Core i7-1165G7",
      RAM: "16GB DDR4",
      Almacenamiento: "512GB SSD",
      Pantalla: '14" Full HD IPS',
      Conectividad: "WiFi 6, Bluetooth 5.1",
    },
  },
  {
    id: 5,
    name: "ASUS ROG Strix G15",
    price: 850000,
    category: "computadoras",
    brand: "ASUS",
    description: "Laptop gamer ASUS ROG con RTX 3070, pantalla 144Hz, ideal para gaming competitivo.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 2,
    specs: {
      Procesador: "AMD Ryzen 7 5800H",
      RAM: "16GB DDR4",
      "Tarjeta Gráfica": "RTX 3070 8GB",
      Pantalla: '15.6" 144Hz',
      Almacenamiento: "1TB SSD",
    },
  },
  {
    id: 6,
    name: "Dell Inspiron 15 3000",
    price: 380000,
    category: "computadoras",
    brand: "Dell",
    description: "Notebook Dell económica para uso básico, ideal para estudiantes y oficina.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Procesador: "Intel Core i3-1115G4",
      RAM: "4GB DDR4",
      Almacenamiento: "128GB SSD",
      Pantalla: '15.6" HD',
      Sistema: "Windows 11 Home",
    },
  },
  {
    id: 7,
    name: "MSI Gaming Desktop",
    price: 750000,
    category: "computadoras",
    brand: "MSI",
    description: "PC de escritorio MSI para gaming, con iluminación RGB y alto rendimiento.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Procesador: "Intel Core i7-12700F",
      RAM: "32GB DDR4",
      "Tarjeta Gráfica": "RTX 3080 10GB",
      Almacenamiento: "1TB SSD NVMe",
      Refrigeración: "Líquida RGB",
    },
  },
  {
    id: 8,
    name: "Acer Aspire 5",
    price: 420000,
    category: "computadoras",
    brand: "Acer",
    description: "Notebook Acer versátil para trabajo y entretenimiento, excelente relación precio-calidad.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Procesador: "AMD Ryzen 5 5500U",
      RAM: "8GB DDR4",
      Almacenamiento: "512GB SSD",
      Pantalla: '15.6" Full HD IPS',
      Batería: "Hasta 8 horas",
    },
  },
  {
    id: 9,
    name: "Surface Laptop 5",
    price: 980000,
    category: "computadoras",
    brand: "Microsoft",
    description: "Microsoft Surface Laptop con pantalla táctil, diseño premium y Windows 11.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Procesador: "Intel Core i5-1235U",
      RAM: "8GB LPDDR5",
      Almacenamiento: "256GB SSD",
      Pantalla: '13.5" PixelSense Touch',
      Peso: "1.29 kg",
    },
  },
  {
    id: 10,
    name: "Chromebook Lenovo IdeaPad",
    price: 280000,
    category: "computadoras",
    brand: "Lenovo",
    description: "Chromebook económico para uso básico, navegación web y aplicaciones de Google.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Procesador: "MediaTek Kompanio 520",
      RAM: "4GB LPDDR4X",
      Almacenamiento: "64GB eMMC",
      Pantalla: '14" HD',
      Sistema: "Chrome OS",
    },
  },

  // CELULARES (10 productos)
  {
    id: 11,
    name: "iPhone 15 Pro 128GB",
    price: 1450000,
    category: "celulares",
    brand: "Apple",
    description: "iPhone 15 Pro con chip A17 Pro, cámara de 48MP y diseño en titanio.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 6,
    specs: {
      Pantalla: '6.1" Super Retina XDR',
      Chip: "A17 Pro",
      Almacenamiento: "128GB",
      Cámara: "48MP + 12MP + 12MP",
      Batería: "Hasta 23 horas de video",
    },
  },
  {
    id: 12,
    name: "Samsung Galaxy S24 Ultra",
    price: 1380000,
    category: "celulares",
    brand: "Samsung",
    description: 'Samsung Galaxy S24 Ultra con S Pen, cámara de 200MP y pantalla de 6.8".',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 4,
    specs: {
      Pantalla: '6.8" Dynamic AMOLED 2X',
      Procesador: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Almacenamiento: "256GB",
      Cámara: "200MP + 50MP + 12MP + 10MP",
    },
  },
  {
    id: 13,
    name: "Xiaomi Redmi Note 13 Pro",
    price: 420000,
    category: "celulares",
    brand: "Xiaomi",
    description: "Xiaomi Redmi Note 13 Pro con carga rápida de 67W y cámara de 200MP.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Pantalla: '6.67" AMOLED',
      Procesador: "Snapdragon 7s Gen 2",
      RAM: "8GB",
      Almacenamiento: "256GB",
      Cámara: "200MP + 8MP + 2MP",
    },
  },
  {
    id: 14,
    name: "Motorola Edge 40 Neo",
    price: 380000,
    category: "celulares",
    brand: "Motorola",
    description: "Motorola Edge 40 Neo con pantalla curva y carga inalámbrica de 15W.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 8,
    specs: {
      Pantalla: '6.55" pOLED',
      Procesador: "Dimensity 7030",
      RAM: "8GB",
      Almacenamiento: "256GB",
      Cámara: "50MP + 13MP",
    },
  },
  {
    id: 15,
    name: "Google Pixel 8",
    price: 850000,
    category: "celulares",
    brand: "Google",
    description: "Google Pixel 8 con chip Tensor G3 y las mejores funciones de IA de Google.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Pantalla: '6.2" OLED',
      Chip: "Google Tensor G3",
      RAM: "8GB",
      Almacenamiento: "128GB",
      Cámara: "50MP + 12MP",
    },
  },
  {
    id: 16,
    name: "OnePlus 12",
    price: 920000,
    category: "celulares",
    brand: "OnePlus",
    description: "OnePlus 12 con carga súper rápida de 100W y pantalla de 120Hz.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 5,
    specs: {
      Pantalla: '6.82" LTPO AMOLED',
      Procesador: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Almacenamiento: "256GB",
      Cámara: "50MP + 64MP + 48MP",
    },
  },
  {
    id: 17,
    name: "Huawei P60 Pro",
    price: 780000,
    category: "celulares",
    brand: "Huawei",
    description: "Huawei P60 Pro con sistema de cámara Leica y diseño premium.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Pantalla: '6.67" OLED',
      Procesador: "Snapdragon 8+ Gen 1",
      RAM: "8GB",
      Almacenamiento: "256GB",
      Cámara: "48MP + 13MP + 48MP Leica",
    },
  },
  {
    id: 18,
    name: "Sony Xperia 1 V",
    price: 1150000,
    category: "celulares",
    brand: "Sony",
    description: "Sony Xperia 1 V con pantalla 4K y tecnología de cámara profesional.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 2,
    specs: {
      Pantalla: '6.5" 4K OLED',
      Procesador: "Snapdragon 8 Gen 2",
      RAM: "12GB",
      Almacenamiento: "256GB",
      Cámara: "48MP + 12MP + 12MP",
    },
  },
  {
    id: 19,
    name: "Realme GT 5 Pro",
    price: 650000,
    category: "celulares",
    brand: "Realme",
    description: "Realme GT 5 Pro con carga de 240W y rendimiento gaming excepcional.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Pantalla: '6.78" AMOLED',
      Procesador: "Snapdragon 8 Gen 3",
      RAM: "12GB",
      Almacenamiento: "256GB",
      Cámara: "50MP + 8MP + 2MP",
    },
  },
  {
    id: 20,
    name: "Nothing Phone 2",
    price: 580000,
    category: "celulares",
    brand: "Nothing",
    description: "Nothing Phone 2 con diseño único transparente y luces LED personalizables.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Pantalla: '6.7" LTPO OLED',
      Procesador: "Snapdragon 8+ Gen 1",
      RAM: "8GB",
      Almacenamiento: "128GB",
      Cámara: "50MP + 50MP",
    },
  },

  // HELADERAS (10 productos)
  {
    id: 21,
    name: "Heladera Samsung No Frost 364L",
    price: 850000,
    category: "heladeras",
    brand: "Samsung",
    description: "Heladera Samsung No Frost con tecnología Twin Cooling Plus y dispensador de agua.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 4,
    specs: {
      Capacidad: "364 litros",
      Tecnología: "No Frost",
      Eficiencia: "A++",
      Dispensador: "Agua fría",
      Dimensiones: "178 x 59.5 x 67.2 cm",
    },
  },
  {
    id: 22,
    name: "Heladera LG Side by Side 601L",
    price: 1250000,
    category: "heladeras",
    brand: "LG",
    description: "Heladera LG Side by Side con dispensador de agua y hielo, tecnología Inverter.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 2,
    specs: {
      Capacidad: "601 litros",
      Tipo: "Side by Side",
      Eficiencia: "A+",
      Dispensador: "Agua y hielo",
      Tecnología: "Inverter Linear",
    },
  },
  {
    id: 23,
    name: "Heladera Whirlpool 265L",
    price: 520000,
    category: "heladeras",
    brand: "Whirlpool",
    description: "Heladera Whirlpool con freezer, ideal para familias pequeñas, bajo consumo.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 8,
    specs: {
      Capacidad: "265 litros",
      Tipo: "Convencional",
      Eficiencia: "A",
      Freezer: "Incluido",
      Color: "Blanco",
    },
  },
  {
    id: 24,
    name: "Heladera Gafa Eternity 410L",
    price: 680000,
    category: "heladeras",
    brand: "Gafa",
    description: "Heladera Gafa Eternity No Frost con control digital y luz LED interior.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 6,
    specs: {
      Capacidad: "410 litros",
      Tecnología: "No Frost",
      Control: "Digital",
      Iluminación: "LED",
      Eficiencia: "A+",
    },
  },
  {
    id: 25,
    name: "Heladera Electrolux French Door 540L",
    price: 1180000,
    category: "heladeras",
    brand: "Electrolux",
    description: "Heladera Electrolux French Door con cajón inferior para congelados y tecnología Frost Free.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Capacidad: "540 litros",
      Tipo: "French Door",
      Tecnología: "Frost Free",
      Cajones: "2 cajones congelador",
      Eficiencia: "A++",
    },
  },
  {
    id: 26,
    name: "Heladera Drean 320L",
    price: 450000,
    category: "heladeras",
    brand: "Drean",
    description: "Heladera Drean económica con freezer superior, perfecta para espacios reducidos.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Capacidad: "320 litros",
      Tipo: "Convencional",
      Freezer: "Superior",
      Eficiencia: "A",
      Garantía: "2 años",
    },
  },
  {
    id: 27,
    name: "Heladera Bosch KGN39VI45",
    price: 980000,
    category: "heladeras",
    brand: "Bosch",
    description: "Heladera Bosch No Frost con tecnología VitaFresh para conservar alimentos frescos por más tiempo.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Capacidad: "366 litros",
      Tecnología: "No Frost + VitaFresh",
      Eficiencia: "A+++",
      Ruido: "39 dB",
      Color: "Acero inoxidable",
    },
  },
  {
    id: 28,
    name: "Heladera Philco 350L",
    price: 580000,
    category: "heladeras",
    brand: "Philco",
    description: "Heladera Philco con dispensador de agua, No Frost y control de temperatura digital.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Capacidad: "350 litros",
      Tecnología: "No Frost",
      Dispensador: "Agua",
      Control: "Digital",
      Eficiencia: "A+",
    },
  },
  {
    id: 29,
    name: "Heladera Midea 420L",
    price: 720000,
    category: "heladeras",
    brand: "Midea",
    description: "Heladera Midea con tecnología Inverter, bajo consumo y diseño moderno.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 5,
    specs: {
      Capacidad: "420 litros",
      Tecnología: "Inverter",
      Eficiencia: "A++",
      Ruido: "38 dB",
      Garantía: "3 años",
    },
  },
  {
    id: 30,
    name: "Heladera Haier 480L",
    price: 890000,
    category: "heladeras",
    brand: "Haier",
    description: "Heladera Haier con múltiples zonas de temperatura y tecnología antibacterial.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Capacidad: "480 litros",
      Zonas: "Multi-temperatura",
      Tecnología: "Antibacterial",
      Eficiencia: "A++",
      Control: "Touch",
    },
  },

  // LAVARROPAS (10 productos)
  {
    id: 31,
    name: "Lavarropas Samsung 8.5kg Carga Frontal",
    price: 650000,
    category: "lavarropas",
    brand: "Samsung",
    description: "Lavarropas Samsung carga frontal con tecnología EcoBubble y 14 programas de lavado.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 6,
    specs: {
      Capacidad: "8.5 kg",
      Tipo: "Carga frontal",
      Tecnología: "EcoBubble",
      Programas: "14",
      Eficiencia: "A+++",
    },
  },
  {
    id: 32,
    name: "Lavarropas LG 10kg Inverter",
    price: 780000,
    category: "lavarropas",
    brand: "LG",
    description: "Lavarropas LG con motor Inverter Direct Drive, 6 Motion y función Steam.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 4,
    specs: {
      Capacidad: "10 kg",
      Motor: "Inverter Direct Drive",
      Tecnología: "6 Motion + Steam",
      Programas: "12",
      Garantía: "10 años motor",
    },
  },
  {
    id: 33,
    name: "Lavarropas Whirlpool 7kg",
    price: 480000,
    category: "lavarropas",
    brand: "Whirlpool",
    description: "Lavarropas Whirlpool carga superior con agitador, ideal para uso familiar.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 9,
    specs: {
      Capacidad: "7 kg",
      Tipo: "Carga superior",
      Agitador: "Incluido",
      Programas: "8",
      Eficiencia: "A+",
    },
  },
  {
    id: 34,
    name: "Lavarropas Drean 6kg Next",
    price: 420000,
    category: "lavarropas",
    brand: "Drean",
    description: "Lavarropas Drean Next con fuzzy logic y múltiples programas de lavado.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 11,
    specs: {
      Capacidad: "6 kg",
      Tecnología: "Fuzzy Logic",
      Tipo: "Carga superior",
      Programas: "10",
      Display: "LED",
    },
  },
  {
    id: 35,
    name: "Lavarropas Bosch 9kg Serie 6",
    price: 920000,
    category: "lavarropas",
    brand: "Bosch",
    description: "Lavarropas Bosch Serie 6 con tecnología i-DOS y función AntiManchas.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Capacidad: "9 kg",
      Tecnología: "i-DOS",
      Función: "AntiManchas",
      Eficiencia: "A+++",
      Ruido: "47 dB",
    },
  },
  {
    id: 36,
    name: "Lavarropas Electrolux 8kg",
    price: 580000,
    category: "lavarropas",
    brand: "Electrolux",
    description: "Lavarropas Electrolux con tecnología Turbo Wash y programa rápido de 15 minutos.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Capacidad: "8 kg",
      Tecnología: "Turbo Wash",
      "Programa rápido": "15 minutos",
      Tipo: "Carga frontal",
      Eficiencia: "A++",
    },
  },
  {
    id: 37,
    name: "Lavarropas Gafa 7.5kg",
    price: 520000,
    category: "lavarropas",
    brand: "Gafa",
    description: "Lavarropas Gafa con control digital y función prelavado, carga superior.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 8,
    specs: {
      Capacidad: "7.5 kg",
      Control: "Digital",
      Función: "Prelavado",
      Tipo: "Carga superior",
      Programas: "9",
    },
  },
  {
    id: 38,
    name: "Lavarropas Philco 6.5kg",
    price: 380000,
    category: "lavarropas",
    brand: "Philco",
    description: "Lavarropas Philco económico con múltiples programas y bajo consumo energético.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 13,
    specs: {
      Capacidad: "6.5 kg",
      Tipo: "Carga superior",
      Programas: "7",
      Eficiencia: "A",
      Garantía: "2 años",
    },
  },
  {
    id: 39,
    name: "Lavarropas Midea 8kg Crown",
    price: 620000,
    category: "lavarropas",
    brand: "Midea",
    description: "Lavarropas Midea Crown con tecnología Inverter y función vapor.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 5,
    specs: {
      Capacidad: "8 kg",
      Tecnología: "Inverter",
      Función: "Vapor",
      Tipo: "Carga frontal",
      Eficiencia: "A+++",
    },
  },
  {
    id: 40,
    name: "Lavarropas Haier 9kg",
    price: 720000,
    category: "lavarropas",
    brand: "Haier",
    description: "Lavarropas Haier con tecnología Direct Motion y programa antibacterial.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Capacidad: "9 kg",
      Tecnología: "Direct Motion",
      Programa: "Antibacterial",
      Tipo: "Carga frontal",
      Eficiencia: "A+++",
    },
  },

  // CAFETERAS (10 productos)
  {
    id: 41,
    name: "Cafetera Nespresso Vertuo Next",
    price: 180000,
    category: "cafeteras",
    brand: "Nespresso",
    description: "Cafetera Nespresso Vertuo Next con tecnología Centrifusion y conectividad Bluetooth.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 8,
    specs: {
      Tecnología: "Centrifusion",
      Conectividad: "Bluetooth",
      Capacidad: "1.1 litros",
      Presión: "19 bares",
      Tamaños: "5 tamaños de taza",
    },
  },
  {
    id: 42,
    name: "Cafetera Dolce Gusto Genio S Plus",
    price: 120000,
    category: "cafeteras",
    brand: "Dolce Gusto",
    description: "Cafetera Dolce Gusto con control de temperatura y presión automática.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 12,
    specs: {
      Presión: "15 bares",
      Capacidad: "0.8 litros",
      Control: "Automático",
      Apagado: "Automático",
      Colores: "Múltiples",
    },
  },
  {
    id: 43,
    name: "Cafetera Express Philips 3200",
    price: 450000,
    category: "cafeteras",
    brand: "Philips",
    description: "Cafetera express Philips con molinillo cerámico y 5 especialidades de café.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Molinillo: "Cerámico",
      Especialidades: "5",
      Presión: "15 bares",
      Capacidad: "1.8 litros",
      Limpieza: "Automática",
    },
  },
  {
    id: 44,
    name: "Cafetera De'Longhi Magnifica S",
    price: 520000,
    category: "cafeteras",
    brand: "De'Longhi",
    description: "Cafetera De'Longhi superautomática con sistema cappuccino y molinillo integrado.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Tipo: "Superautomática",
      Sistema: "Cappuccino",
      Molinillo: "Integrado",
      Presión: "15 bares",
      Capacidad: "1.8 litros",
    },
  },
  {
    id: 45,
    name: "Cafetera Oster Prima Latte",
    price: 85000,
    category: "cafeteras",
    brand: "Oster",
    description: "Cafetera Oster con vaporizador para leche y filtro permanente.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Vaporizador: "Incluido",
      Filtro: "Permanente",
      Capacidad: "1.25 litros",
      Presión: "15 bares",
      Material: "Acero inoxidable",
    },
  },
  {
    id: 46,
    name: "Cafetera Breville Barista Express",
    price: 680000,
    category: "cafeteras",
    brand: "Breville",
    description: "Cafetera Breville profesional con molinillo cónico y control de temperatura PID.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 2,
    specs: {
      Molinillo: "Cónico integrado",
      Control: "PID",
      Presión: "15 bares",
      Precalentamiento: "3 segundos",
      Vaporizador: "360°",
    },
  },
  {
    id: 47,
    name: "Cafetera Moulinex Subito",
    price: 45000,
    category: "cafeteras",
    brand: "Moulinex",
    description: "Cafetera Moulinex de filtro con jarra de vidrio y placa calefactora.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 20,
    specs: {
      Tipo: "Filtro",
      Jarra: "Vidrio",
      Capacidad: "1.25 litros",
      "Placa calefactora": "Incluida",
      Filtro: "Permanente",
    },
  },
  {
    id: 48,
    name: "Cafetera Krups Nescafé Dolce Gusto",
    price: 95000,
    category: "cafeteras",
    brand: "Krups",
    description: "Cafetera Krups para cápsulas Dolce Gusto con sistema de presión profesional.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 10,
    specs: {
      Sistema: "Cápsulas",
      Presión: "15 bares",
      Capacidad: "0.8 litros",
      Bebidas: "Frías y calientes",
      Apagado: "Automático",
    },
  },
  {
    id: 49,
    name: "Cafetera Saeco PicoBaristo",
    price: 780000,
    category: "cafeteras",
    brand: "Saeco",
    description: "Cafetera Saeco superautomática con 10 especialidades y molinillo cerámico.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 1,
    specs: {
      Especialidades: "10",
      Molinillo: "Cerámico",
      Tipo: "Superautomática",
      Capacidad: "1.8 litros",
      Limpieza: "Automática",
    },
  },
  {
    id: 50,
    name: "Cafetera Black & Decker CM1160B",
    price: 65000,
    category: "cafeteras",
    brand: "Black & Decker",
    description: "Cafetera Black & Decker programable con jarra térmica y filtro permanente.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 18,
    specs: {
      Tipo: "Programable",
      Jarra: "Térmica",
      Capacidad: "12 tazas",
      Timer: "24 horas",
      Filtro: "Permanente",
    },
  },

  // TELEVISORES (10 productos)
  {
    id: 51,
    name: 'Smart TV Samsung 55" 4K QLED',
    price: 850000,
    category: "televisores",
    brand: "Samsung",
    description: 'Smart TV Samsung QLED 55" con tecnología Quantum Dot y procesador Crystal 4K.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 6,
    specs: {
      Tamaño: "55 pulgadas",
      Resolución: "4K UHD",
      Tecnología: "QLED",
      "Sistema operativo": "Tizen",
      HDR: "HDR10+",
    },
  },
  {
    id: 52,
    name: 'Smart TV LG 65" OLED C3',
    price: 1450000,
    category: "televisores",
    brand: "LG",
    description: 'Smart TV LG OLED 65" con procesador α9 Gen6 AI y Dolby Vision IQ.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 3,
    specs: {
      Tamaño: "65 pulgadas",
      Tecnología: "OLED",
      Procesador: "α9 Gen6 AI",
      "Sistema operativo": "webOS",
      Gaming: "120Hz VRR",
    },
  },
  {
    id: 53,
    name: 'Smart TV Sony 50" 4K LED',
    price: 680000,
    category: "televisores",
    brand: "Sony",
    description: 'Smart TV Sony 50" con procesador X1 y tecnología TRILUMINOS PRO.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 8,
    specs: {
      Tamaño: "50 pulgadas",
      Procesador: "X1",
      Tecnología: "TRILUMINOS PRO",
      "Sistema operativo": "Google TV",
      Audio: "Dolby Atmos",
    },
  },
  {
    id: 54,
    name: 'Smart TV TCL 43" 4K Android',
    price: 420000,
    category: "televisores",
    brand: "TCL",
    description: 'Smart TV TCL 43" con Android TV y tecnología HDR10.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Tamaño: "43 pulgadas",
      "Sistema operativo": "Android TV",
      HDR: "HDR10",
      Conectividad: "WiFi + Bluetooth",
      Puertos: "3 HDMI, 2 USB",
    },
  },
  {
    id: 55,
    name: 'Smart TV Philips 58" 4K Ambilight',
    price: 780000,
    category: "televisores",
    brand: "Philips",
    description: 'Smart TV Philips 58" con tecnología Ambilight y procesador P5 Perfect Picture.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Tamaño: "58 pulgadas",
      Tecnología: "Ambilight",
      Procesador: "P5 Perfect Picture",
      "Sistema operativo": "Android TV",
      HDR: "HDR10+ y Dolby Vision",
    },
  },
  {
    id: 56,
    name: 'Smart TV Hisense 40" Full HD',
    price: 320000,
    category: "televisores",
    brand: "Hisense",
    description: 'Smart TV Hisense 40" Full HD con VIDAA Smart OS y control por voz.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Tamaño: "40 pulgadas",
      Resolución: "Full HD",
      "Sistema operativo": "VIDAA",
      "Control por voz": "Incluido",
      Conectividad: "WiFi integrado",
    },
  },
  {
    id: 57,
    name: 'Smart TV Noblex 32" HD',
    price: 250000,
    category: "televisores",
    brand: "Noblex",
    description: 'Smart TV Noblex 32" HD con Netflix y YouTube integrados.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 20,
    specs: {
      Tamaño: "32 pulgadas",
      Resolución: "HD Ready",
      Apps: "Netflix, YouTube",
      Conectividad: "WiFi",
      Puertos: "2 HDMI, 1 USB",
    },
  },
  {
    id: 58,
    name: 'Smart TV Xiaomi 55" 4K',
    price: 520000,
    category: "televisores",
    brand: "Xiaomi",
    description: 'Smart TV Xiaomi 55" 4K con Android TV y control por voz Google Assistant.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Tamaño: "55 pulgadas",
      "Sistema operativo": "Android TV",
      Asistente: "Google Assistant",
      HDR: "HDR10",
      Conectividad: "WiFi 5 + Bluetooth",
    },
  },
  {
    id: 59,
    name: 'Smart TV RCA 24" HD',
    price: 180000,
    category: "televisores",
    brand: "RCA",
    description: 'Smart TV RCA 24" HD compacta, ideal para dormitorios y espacios pequeños.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 25,
    specs: {
      Tamaño: "24 pulgadas",
      Resolución: "HD Ready",
      Tipo: "LED",
      Conectividad: "WiFi",
      Uso: "Ideal para dormitorios",
    },
  },
  {
    id: 60,
    name: 'Smart TV Panasonic 60" 4K',
    price: 920000,
    category: "televisores",
    brand: "Panasonic",
    description: 'Smart TV Panasonic 60" 4K con tecnología HCX Pro AI y My Home Screen.',
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Tamaño: "60 pulgadas",
      Procesador: "HCX Pro AI",
      "Sistema operativo": "My Home Screen",
      HDR: "HDR10+ y Dolby Vision",
      Audio: "Dolby Atmos",
    },
  },

  // AIRES ACONDICIONADOS (10 productos)
  {
    id: 61,
    name: "Aire Acondicionado Samsung 3000W Split",
    price: 520000,
    category: "aires",
    brand: "Samsung",
    description: "Aire acondicionado Samsung Split 3000W con tecnología Inverter y WiFi.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 8,
    specs: {
      Potencia: "3000W",
      Tecnología: "Inverter",
      Conectividad: "WiFi",
      Eficiencia: "A++",
      Cobertura: "25 m²",
    },
  },
  {
    id: 62,
    name: "Aire Acondicionado LG 4500W Dual Inverter",
    price: 680000,
    category: "aires",
    brand: "LG",
    description: "Aire acondicionado LG Dual Inverter 4500W con compresor rotativo y bajo ruido.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 5,
    specs: {
      Potencia: "4500W",
      Tecnología: "Dual Inverter",
      Compresor: "Rotativo",
      Ruido: "19 dB",
      Cobertura: "35 m²",
    },
  },
  {
    id: 63,
    name: "Aire Acondicionado Midea 2200W",
    price: 380000,
    category: "aires",
    brand: "Midea",
    description: "Aire acondicionado Midea 2200W económico con función sleep y timer.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Potencia: "2200W",
      Función: "Sleep + Timer",
      Eficiencia: "A",
      Cobertura: "18 m²",
      Garantía: "2 años",
    },
  },
  {
    id: 64,
    name: "Aire Acondicionado Carrier 5200W",
    price: 750000,
    category: "aires",
    brand: "Carrier",
    description: "Aire acondicionado Carrier 5200W con tecnología Inverter y filtro antibacterial.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Potencia: "5200W",
      Filtro: "Antibacterial",
      Tecnología: "Inverter",
      Eficiencia: "A+++",
      Cobertura: "40 m²",
    },
  },
  {
    id: 65,
    name: "Aire Acondicionado Philco 3500W",
    price: 450000,
    category: "aires",
    brand: "Philco",
    description: "Aire acondicionado Philco 3500W con control remoto y función deshumidificador.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 9,
    specs: {
      Potencia: "3500W",
      Control: "Remoto",
      Función: "Deshumidificador",
      Cobertura: "28 m²",
      Eficiencia: "A+",
    },
  },
  {
    id: 66,
    name: "Aire Acondicionado Daikin 6000W",
    price: 920000,
    category: "aires",
    brand: "Daikin",
    description: "Aire acondicionado Daikin 6000W profesional con tecnología Flash Streamer.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Potencia: "6000W",
      Tecnología: "Flash Streamer",
      Purificación: "Aire",
      Eficiencia: "A+++",
      Cobertura: "50 m²",
    },
  },
  {
    id: 67,
    name: "Aire Acondicionado BGH 2800W",
    price: 420000,
    category: "aires",
    brand: "BGH",
    description: "Aire acondicionado BGH 2800W con gas ecológico R32 y bajo consumo.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 11,
    specs: {
      Potencia: "2800W",
      Gas: "R32 Ecológico",
      Consumo: "Bajo",
      Cobertura: "22 m²",
      Eficiencia: "A+",
    },
  },
  {
    id: 68,
    name: "Aire Acondicionado Electrolux 4000W",
    price: 580000,
    category: "aires",
    brand: "Electrolux",
    description: "Aire acondicionado Electrolux 4000W con función turbo y filtro lavable.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 6,
    specs: {
      Potencia: "4000W",
      Función: "Turbo",
      Filtro: "Lavable",
      Cobertura: "32 m²",
      Eficiencia: "A++",
    },
  },
  {
    id: 69,
    name: "Aire Acondicionado Surrey 3200W",
    price: 480000,
    category: "aires",
    brand: "Surrey",
    description: "Aire acondicionado Surrey 3200W con display LED y función auto-restart.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Potencia: "3200W",
      Display: "LED",
      Función: "Auto-restart",
      Cobertura: "26 m²",
      Garantía: "3 años",
    },
  },
  {
    id: 70,
    name: "Aire Acondicionado Hitachi 5500W",
    price: 820000,
    category: "aires",
    brand: "Hitachi",
    description: "Aire acondicionado Hitachi 5500W con compresor scroll y tecnología Inverter avanzada.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Potencia: "5500W",
      Compresor: "Scroll",
      Tecnología: "Inverter avanzada",
      Cobertura: "45 m²",
      Eficiencia: "A+++",
    },
  },

  // MICROONDAS (10 productos)
  {
    id: 71,
    name: "Microondas Samsung 28L Digital",
    price: 180000,
    category: "microondas",
    brand: "Samsung",
    description: "Microondas Samsung 28L con grill, panel digital y 10 niveles de potencia.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 10,
    specs: {
      Capacidad: "28 litros",
      Grill: "Incluido",
      Panel: "Digital",
      Potencia: "900W",
      Programas: "10",
    },
  },
  {
    id: 72,
    name: "Microondas LG 25L NeoChef",
    price: 220000,
    category: "microondas",
    brand: "LG",
    description: "Microondas LG NeoChef con tecnología Smart Inverter y interior EasyClean.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 8,
    specs: {
      Capacidad: "25 litros",
      Tecnología: "Smart Inverter",
      Interior: "EasyClean",
      Potencia: "1000W",
      Control: "Touch",
    },
  },
  {
    id: 73,
    name: "Microondas Whirlpool 20L",
    price: 120000,
    category: "microondas",
    brand: "Whirlpool",
    description: "Microondas Whirlpool 20L básico con 5 niveles de potencia y timer.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Capacidad: "20 litros",
      Niveles: "5",
      Timer: "30 minutos",
      Potencia: "700W",
      Tipo: "Solo microondas",
    },
  },
  {
    id: 74,
    name: "Microondas Panasonic 32L Inverter",
    price: 280000,
    category: "microondas",
    brand: "Panasonic",
    description: "Microondas Panasonic 32L con tecnología Inverter y función vapor.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Capacidad: "32 litros",
      Tecnología: "Inverter",
      Función: "Vapor",
      Potencia: "1100W",
      Programas: "15",
    },
  },
  {
    id: 75,
    name: "Microondas Electrolux 23L",
    price: 150000,
    category: "microondas",
    brand: "Electrolux",
    description: "Microondas Electrolux 23L con grill y función descongelado automático.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Capacidad: "23 litros",
      Grill: "Incluido",
      Descongelado: "Automático",
      Potencia: "800W",
      Display: "LED",
    },
  },
  {
    id: 76,
    name: "Microondas Philco 30L",
    price: 160000,
    category: "microondas",
    brand: "Philco",
    description: "Microondas Philco 30L con grill y 8 programas preestablecidos.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 9,
    specs: {
      Capacidad: "30 litros",
      Programas: "8",
      Grill: "Incluido",
      Potencia: "900W",
      Plato: "Giratorio",
    },
  },
  {
    id: 77,
    name: "Microondas Sharp 25L Carousel",
    price: 190000,
    category: "microondas",
    brand: "Sharp",
    description: "Microondas Sharp Carousel 25L con sistema de ondas uniformes.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 6,
    specs: {
      Capacidad: "25 litros",
      Sistema: "Carousel",
      Ondas: "Uniformes",
      Potencia: "900W",
      Control: "Digital",
    },
  },
  {
    id: 78,
    name: "Microondas Midea 26L",
    price: 140000,
    category: "microondas",
    brand: "Midea",
    description: "Microondas Midea 26L con función grill y panel táctil.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 11,
    specs: {
      Capacidad: "26 litros",
      Panel: "Táctil",
      Grill: "Incluido",
      Potencia: "900W",
      Seguridad: "Bloqueo infantil",
    },
  },
  {
    id: 79,
    name: "Microondas Daewoo 18L",
    price: 95000,
    category: "microondas",
    brand: "Daewoo",
    description: "Microondas Daewoo 18L compacto, ideal para espacios pequeños.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 18,
    specs: {
      Capacidad: "18 litros",
      Tamaño: "Compacto",
      Potencia: "700W",
      Niveles: "5",
      Uso: "Espacios pequeños",
    },
  },
  {
    id: 80,
    name: "Microondas Bosch 21L",
    price: 250000,
    category: "microondas",
    brand: "Bosch",
    description: "Microondas Bosch 21L empotrable con función AutoPilot y vapor.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Capacidad: "21 litros",
      Tipo: "Empotrable",
      Función: "AutoPilot",
      Vapor: "Incluido",
      Potencia: "900W",
    },
  },

  // ASPIRADORAS (10 productos)
  {
    id: 81,
    name: "Aspiradora Dyson V15 Detect",
    price: 850000,
    category: "aspiradoras",
    brand: "Dyson",
    description: "Aspiradora Dyson V15 Detect inalámbrica con láser y sensor de partículas.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 5,
    specs: {
      Tipo: "Inalámbrica",
      Tecnología: "Láser + Sensor",
      Batería: "60 minutos",
      Filtro: "HEPA",
      Accesorios: "8 incluidos",
    },
  },
  {
    id: 82,
    name: "Aspiradora Shark Navigator",
    price: 320000,
    category: "aspiradoras",
    brand: "Shark",
    description: "Aspiradora Shark Navigator con tecnología Anti-Wrap y filtro HEPA.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 8,
    specs: {
      Tecnología: "Anti-Wrap",
      Filtro: "HEPA",
      Capacidad: "3.5 litros",
      Cable: "8 metros",
      Peso: "6.8 kg",
    },
  },
  {
    id: 83,
    name: "Aspiradora Electrolux Spin",
    price: 180000,
    category: "aspiradoras",
    brand: "Electrolux",
    description: "Aspiradora Electrolux Spin con bolsa, motor de 1400W y filtro lavable.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 12,
    specs: {
      Motor: "1400W",
      Tipo: "Con bolsa",
      Filtro: "Lavable",
      Cable: "6 metros",
      Accesorios: "3 incluidos",
    },
  },
  {
    id: 84,
    name: "Aspiradora Black & Decker 1200W",
    price: 120000,
    category: "aspiradoras",
    brand: "Black & Decker",
    description: "Aspiradora Black & Decker 1200W sin bolsa con filtro ciclónico.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Motor: "1200W",
      Tipo: "Sin bolsa",
      Filtro: "Ciclónico",
      Capacidad: "2 litros",
      Peso: "4.5 kg",
    },
  },
  {
    id: 85,
    name: "Aspiradora Philips PowerPro",
    price: 250000,
    category: "aspiradoras",
    brand: "Philips",
    description: "Aspiradora Philips PowerPro con tecnología PowerCyclone y cepillo TriActive.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Tecnología: "PowerCyclone",
      Cepillo: "TriActive",
      Motor: "1800W",
      Capacidad: "2.5 litros",
      Filtro: "EPA",
    },
  },
  {
    id: 86,
    name: "Aspiradora Robot iRobot Roomba",
    price: 680000,
    category: "aspiradoras",
    brand: "iRobot",
    description: "Aspiradora robot iRobot Roomba con mapeo inteligente y control por app.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 6,
    specs: {
      Tipo: "Robot",
      Mapeo: "Inteligente",
      Control: "App móvil",
      Batería: "90 minutos",
      Recarga: "Automática",
    },
  },
  {
    id: 87,
    name: "Aspiradora Karcher WD3",
    price: 280000,
    category: "aspiradoras",
    brand: "Karcher",
    description: "Aspiradora Karcher WD3 para sólidos y líquidos con función soplador.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 9,
    specs: {
      Tipo: "Sólidos y líquidos",
      Función: "Soplador",
      Capacidad: "17 litros",
      Motor: "1000W",
      Manguera: "2 metros",
    },
  },
  {
    id: 88,
    name: "Aspiradora Oster 1600W",
    price: 150000,
    category: "aspiradoras",
    brand: "Oster",
    description: "Aspiradora Oster 1600W con bolsa y sistema de filtrado múltiple.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 11,
    specs: {
      Motor: "1600W",
      Tipo: "Con bolsa",
      Filtrado: "Múltiple",
      Cable: "5 metros",
      Garantía: "2 años",
    },
  },
  {
    id: 89,
    name: "Aspiradora Bissell CrossWave",
    price: 420000,
    category: "aspiradoras",
    brand: "Bissell",
    description: "Aspiradora Bissell CrossWave que aspira y trapea simultáneamente.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 4,
    specs: {
      Función: "Aspira y trapea",
      Tanques: "Agua limpia y sucia",
      Superficies: "Múltiples",
      Cable: "7.5 metros",
      Peso: "5.2 kg",
    },
  },
  {
    id: 90,
    name: "Aspiradora Tineco Pure ONE S12",
    price: 380000,
    category: "aspiradoras",
    brand: "Tineco",
    description: "Aspiradora Tineco Pure ONE S12 inalámbrica con sensor inteligente.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 7,
    specs: {
      Tipo: "Inalámbrica",
      Sensor: "Inteligente",
      Batería: "35 minutos",
      Display: "LED",
      Filtro: "HEPA",
    },
  },

  // PARLANTES (10 productos)
  {
    id: 91,
    name: "Parlante JBL Charge 5",
    price: 180000,
    category: "parlantes",
    brand: "JBL",
    description: "Parlante JBL Charge 5 portátil con Bluetooth, resistente al agua IP67.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 12,
    specs: {
      Conectividad: "Bluetooth 5.1",
      Resistencia: "IP67",
      Batería: "20 horas",
      Potencia: "30W",
      "Power Bank": "Incluido",
    },
  },
  {
    id: 92,
    name: "Parlante Sony SRS-XB43",
    price: 220000,
    category: "parlantes",
    brand: "Sony",
    description: "Parlante Sony SRS-XB43 con Extra Bass y luces LED sincronizadas.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: true,
    stock: 8,
    specs: {
      Tecnología: "Extra Bass",
      Luces: "LED sincronizadas",
      Batería: "24 horas",
      Resistencia: "IP67",
      Conectividad: "Bluetooth + NFC",
    },
  },
  {
    id: 93,
    name: "Parlante Bose SoundLink Mini",
    price: 320000,
    category: "parlantes",
    brand: "Bose",
    description: "Parlante Bose SoundLink Mini compacto con sonido premium y diseño elegante.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 6,
    specs: {
      Tamaño: "Compacto",
      Sonido: "Premium",
      Batería: "12 horas",
      Peso: "680g",
      Conectividad: "Bluetooth",
    },
  },
  {
    id: 94,
    name: "Parlante Marshall Kilburn II",
    price: 450000,
    category: "parlantes",
    brand: "Marshall",
    description: "Parlante Marshall Kilburn II con diseño vintage y sonido de guitarra icónico.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 0,
    specs: {
      Diseño: "Vintage",
      Sonido: "Icónico Marshall",
      Batería: "20+ horas",
      Resistencia: "IPX2",
      Potencia: "36W",
    },
  },
  {
    id: 95,
    name: "Parlante Xiaomi Mi Portable",
    price: 85000,
    category: "parlantes",
    brand: "Xiaomi",
    description: "Parlante Xiaomi Mi Portable económico con Bluetooth 5.0 y micrófono integrado.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 20,
    specs: {
      Conectividad: "Bluetooth 5.0",
      Micrófono: "Integrado",
      Batería: "13 horas",
      Peso: "500g",
      Precio: "Económico",
    },
  },
  {
    id: 96,
    name: "Parlante Harman Kardon Onyx Studio",
    price: 380000,
    category: "parlantes",
    brand: "Harman Kardon",
    description: "Parlante Harman Kardon Onyx Studio con diseño circular y sonido 360°.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 5,
    specs: {
      Diseño: "Circular",
      Sonido: "360°",
      Batería: "8 horas",
      Conectividad: "Bluetooth",
      Potencia: "50W",
    },
  },
  {
    id: 97,
    name: "Parlante Ultimate Ears Boom 3",
    price: 280000,
    category: "parlantes",
    brand: "Ultimate Ears",
    description: "Parlante Ultimate Ears Boom 3 con sonido 360° y resistencia extrema.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 9,
    specs: {
      Sonido: "360°",
      Resistencia: "IP67",
      Batería: "15 horas",
      Flotante: "Sí",
      App: "Control remoto",
    },
  },
  {
    id: 98,
    name: "Parlante Anker Soundcore 2",
    price: 120000,
    category: "parlantes",
    brand: "Anker",
    description: "Parlante Anker Soundcore 2 con tecnología BassUp y 24 horas de batería.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 15,
    specs: {
      Tecnología: "BassUp",
      Batería: "24 horas",
      Resistencia: "IPX7",
      Conectividad: "Bluetooth 5.0",
      Peso: "414g",
    },
  },
  {
    id: 99,
    name: "Parlante Bang & Olufsen Beosound A1",
    price: 520000,
    category: "parlantes",
    brand: "Bang & Olufsen",
    description: "Parlante Bang & Olufsen Beosound A1 premium con diseño danés y sonido Hi-Fi.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 3,
    specs: {
      Diseño: "Danés premium",
      Sonido: "Hi-Fi",
      Batería: "18 horas",
      Resistencia: "IP67",
      Materiales: "Aluminio",
    },
  },
  {
    id: 100,
    name: "Parlante Edifier R1280T",
    price: 150000,
    category: "parlantes",
    brand: "Edifier",
    description: "Parlantes Edifier R1280T de escritorio con madera natural y sonido estéreo.",
    image: "/placeholder.svg?height=400&width=400",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    featured: false,
    stock: 11,
    specs: {
      Tipo: "Escritorio",
      Material: "Madera natural",
      Sonido: "Estéreo",
      Potencia: "42W",
      Conectividad: "RCA + AUX",
    },
  },
]

// Función para obtener productos
function getProducts() {
  return products
}

// Función para obtener producto por ID
function getProductById(id) {
  return products.find((product) => product.id === Number.parseInt(id))
}

// Función para obtener productos destacados
function getFeaturedProducts() {
  return products.filter((product) => product.featured)
}

// Función para obtener productos por categoría
function getProductsByCategory(category) {
  return products.filter((product) => product.category === category)
}

// Función para obtener productos por marca
function getProductsByBrand(brand) {
  return products.filter((product) => product.brand === brand)
}

// Función para buscar productos
function searchProducts(query) {
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(query.toLowerCase()) ||
      product.description.toLowerCase().includes(query.toLowerCase()) ||
      product.brand.toLowerCase().includes(query.toLowerCase()),
  )
}

// Función para filtrar productos
function filterProducts(filters) {
  let filteredProducts = [...products]

  if (filters.category) {
    filteredProducts = filteredProducts.filter((product) => product.category === filters.category)
  }

  if (filters.brand) {
    filteredProducts = filteredProducts.filter((product) => product.brand === filters.brand)
  }

  if (filters.minPrice) {
    filteredProducts = filteredProducts.filter((product) => product.price >= filters.minPrice)
  }

  if (filters.maxPrice) {
    filteredProducts = filteredProducts.filter((product) => product.price <= filters.maxPrice)
  }

  if (filters.search) {
    filteredProducts = filteredProducts.filter(
      (product) =>
        product.name.toLowerCase().includes(filters.search.toLowerCase()) ||
        product.description.toLowerCase().includes(filters.search.toLowerCase()) ||
        product.brand.toLowerCase().includes(filters.search.toLowerCase()),
    )
  }

  if (filters.inStock) {
    filteredProducts = filteredProducts.filter((product) => product.stock > 0)
  }

  // Ordenar productos
  if (filters.sort) {
    switch (filters.sort) {
      case "price-low":
        filteredProducts.sort((a, b) => a.price - b.price)
        break
      case "price-high":
        filteredProducts.sort((a, b) => b.price - a.price)
        break
      case "name":
        filteredProducts.sort((a, b) => a.name.localeCompare(b.name))
        break
      case "brand":
        filteredProducts.sort((a, b) => a.brand.localeCompare(b.brand))
        break
    }
  }

  return filteredProducts
}

// Función para obtener todas las categorías
function getCategories() {
  return [...new Set(products.map((product) => product.category))]
}

// Función para obtener todas las marcas
function getBrands() {
  return [...new Set(products.map((product) => product.brand))]
}

// Función para obtener marcas por categoría
function getBrandsByCategory(category) {
  return [...new Set(products.filter((product) => product.category === category).map((product) => product.brand))]
}
